### PR TITLE
CSS Modules

### PR DESCRIPTION
**Pull request by bitpshr**
This PR adds CSS modules to the Monster Cards example project. Some notes:
- We're using PostCSS in the Gruntfile because dojo/cli-css-modules#1 hasn't landed. We can remove this in favor of the CLI in the future.
- There's not much structural CSS for the current widgets, so the modules are small. The PR at least gets things in place and working as a foundation for future widget dev.

Refs #60.

### CODE REVIEW

**Comment by Tomdye** [comment]
shouldn't all the `css` files be gitIgnored?

**Comment by bitpshr** [comment]
@Tomdye yes, and the generated TS files should've also been ignored. Good catch. Fixed.

**Comment by kitsonk** [comment]
As pointed out by @matt-gadd this would have to be reworked to fit our current build tooling.  We need to address that.

**Comment by agubler** [comment]
@bitpshr there are lots of conflicts after the latest refactors, is this something you need to redo after landing CSS modules in `dojo-cli-build-webpack`?

**Comment by bitpshr** [comment]
@agubler Yeah, this definitely needs major rework. I think it makes sense to close this in favor of a fresh PR since PostCSS isn't necessary and the Monster Cards app itself has changed significantly.

**Pull request closed without merging**
