### PR TITLE
Re-Write showcase

### PR DESCRIPTION
**Pull request by tomdye**
Re-write of showcase to resemble dojo 1.x theme tester
- uses `@dojo/themes` repo

screenshot 2018-02-07 13 45 14

resolves: #247  
resolves: #280
resolves: #278

### CODE REVIEW

**Comment by dylans** [comment]
This supersedes #279 , though you may want to add a Toolbar into this PR as I don't see it in the code.

**Comment by tomdye** [comment]
@dylans there's a toolbar at the top with the title in it

**Comment by tomdye** [comment]
@agubler does this need a further process to get published to github.io?

**Comment by agubler** [comment]
@tomdye I think it should just get deployed!

**Pull request merged**
